/**
 * @file MonsterEncounterTables.ts
 * @description Exhaustive bestiary encounter tables with stat scalers, elite affixes, and dungeon zone spawn weights.
 */

export interface MonsterArchetype {
  id: string;
  name: string;
  baseHealth: number;
  baseDamage: number;
  baseSpeed: number;
  experienceValue: number;
  resistances: { fire: number; cold: number; lightning: number; physical: number };
  behaviorTreeType: 'melee_swarmer' | 'ranged_caster' | 'boss_titans' | 'stealth_ambusher';
}

export const BESTIARY: MonsterArchetype[] = [
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 95,
    baseDamage: 14,
    baseSpeed: 100,
    experienceValue: 55,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 115,
    baseDamage: 17,
    baseSpeed: 110,
    experienceValue: 70,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 135,
    baseDamage: 20,
    baseSpeed: 120,
    experienceValue: 85,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 2,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 155,
    baseDamage: 23,
    baseSpeed: 130,
    experienceValue: 100,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 175,
    baseDamage: 26,
    baseSpeed: 140,
    experienceValue: 115,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 195,
    baseDamage: 29,
    baseSpeed: 100,
    experienceValue: 130,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 2,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 215,
    baseDamage: 32,
    baseSpeed: 110,
    experienceValue: 145,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 235,
    baseDamage: 35,
    baseSpeed: 120,
    experienceValue: 160,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 255,
    baseDamage: 38,
    baseSpeed: 130,
    experienceValue: 175,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 2,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 275,
    baseDamage: 41,
    baseSpeed: 140,
    experienceValue: 190,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 295,
    baseDamage: 44,
    baseSpeed: 100,
    experienceValue: 205,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 315,
    baseDamage: 47,
    baseSpeed: 110,
    experienceValue: 220,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 2,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 335,
    baseDamage: 50,
    baseSpeed: 120,
    experienceValue: 235,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 355,
    baseDamage: 53,
    baseSpeed: 130,
    experienceValue: 250,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 2,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 375,
    baseDamage: 56,
    baseSpeed: 140,
    experienceValue: 265,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 2,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 140,
    baseDamage: 20,
    baseSpeed: 100,
    experienceValue: 85,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 160,
    baseDamage: 23,
    baseSpeed: 110,
    experienceValue: 100,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 180,
    baseDamage: 26,
    baseSpeed: 120,
    experienceValue: 115,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 4,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 200,
    baseDamage: 29,
    baseSpeed: 130,
    experienceValue: 130,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 220,
    baseDamage: 32,
    baseSpeed: 140,
    experienceValue: 145,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 240,
    baseDamage: 35,
    baseSpeed: 100,
    experienceValue: 160,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 4,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 260,
    baseDamage: 38,
    baseSpeed: 110,
    experienceValue: 175,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 280,
    baseDamage: 41,
    baseSpeed: 120,
    experienceValue: 190,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 300,
    baseDamage: 44,
    baseSpeed: 130,
    experienceValue: 205,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 4,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 320,
    baseDamage: 47,
    baseSpeed: 140,
    experienceValue: 220,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 340,
    baseDamage: 50,
    baseSpeed: 100,
    experienceValue: 235,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 360,
    baseDamage: 53,
    baseSpeed: 110,
    experienceValue: 250,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 4,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 380,
    baseDamage: 56,
    baseSpeed: 120,
    experienceValue: 265,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 400,
    baseDamage: 59,
    baseSpeed: 130,
    experienceValue: 280,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 4,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 420,
    baseDamage: 62,
    baseSpeed: 140,
    experienceValue: 295,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 4,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 185,
    baseDamage: 26,
    baseSpeed: 100,
    experienceValue: 115,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 205,
    baseDamage: 29,
    baseSpeed: 110,
    experienceValue: 130,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 225,
    baseDamage: 32,
    baseSpeed: 120,
    experienceValue: 145,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 6,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 245,
    baseDamage: 35,
    baseSpeed: 130,
    experienceValue: 160,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 265,
    baseDamage: 38,
    baseSpeed: 140,
    experienceValue: 175,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 285,
    baseDamage: 41,
    baseSpeed: 100,
    experienceValue: 190,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 6,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 305,
    baseDamage: 44,
    baseSpeed: 110,
    experienceValue: 205,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 325,
    baseDamage: 47,
    baseSpeed: 120,
    experienceValue: 220,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 345,
    baseDamage: 50,
    baseSpeed: 130,
    experienceValue: 235,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 6,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 365,
    baseDamage: 53,
    baseSpeed: 140,
    experienceValue: 250,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 385,
    baseDamage: 56,
    baseSpeed: 100,
    experienceValue: 265,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 405,
    baseDamage: 59,
    baseSpeed: 110,
    experienceValue: 280,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 6,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 425,
    baseDamage: 62,
    baseSpeed: 120,
    experienceValue: 295,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 445,
    baseDamage: 65,
    baseSpeed: 130,
    experienceValue: 310,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 6,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 465,
    baseDamage: 68,
    baseSpeed: 140,
    experienceValue: 325,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 6,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 230,
    baseDamage: 32,
    baseSpeed: 100,
    experienceValue: 145,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 250,
    baseDamage: 35,
    baseSpeed: 110,
    experienceValue: 160,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 270,
    baseDamage: 38,
    baseSpeed: 120,
    experienceValue: 175,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 8,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 290,
    baseDamage: 41,
    baseSpeed: 130,
    experienceValue: 190,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 310,
    baseDamage: 44,
    baseSpeed: 140,
    experienceValue: 205,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 330,
    baseDamage: 47,
    baseSpeed: 100,
    experienceValue: 220,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 8,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 350,
    baseDamage: 50,
    baseSpeed: 110,
    experienceValue: 235,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 370,
    baseDamage: 53,
    baseSpeed: 120,
    experienceValue: 250,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 390,
    baseDamage: 56,
    baseSpeed: 130,
    experienceValue: 265,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 8,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 410,
    baseDamage: 59,
    baseSpeed: 140,
    experienceValue: 280,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 430,
    baseDamage: 62,
    baseSpeed: 100,
    experienceValue: 295,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 450,
    baseDamage: 65,
    baseSpeed: 110,
    experienceValue: 310,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 8,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 470,
    baseDamage: 68,
    baseSpeed: 120,
    experienceValue: 325,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 490,
    baseDamage: 71,
    baseSpeed: 130,
    experienceValue: 340,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 8,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 510,
    baseDamage: 74,
    baseSpeed: 140,
    experienceValue: 355,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 8,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 275,
    baseDamage: 38,
    baseSpeed: 100,
    experienceValue: 175,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 295,
    baseDamage: 41,
    baseSpeed: 110,
    experienceValue: 190,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 315,
    baseDamage: 44,
    baseSpeed: 120,
    experienceValue: 205,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 10,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 335,
    baseDamage: 47,
    baseSpeed: 130,
    experienceValue: 220,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 355,
    baseDamage: 50,
    baseSpeed: 140,
    experienceValue: 235,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 375,
    baseDamage: 53,
    baseSpeed: 100,
    experienceValue: 250,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 10,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 395,
    baseDamage: 56,
    baseSpeed: 110,
    experienceValue: 265,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 415,
    baseDamage: 59,
    baseSpeed: 120,
    experienceValue: 280,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 435,
    baseDamage: 62,
    baseSpeed: 130,
    experienceValue: 295,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 10,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 455,
    baseDamage: 65,
    baseSpeed: 140,
    experienceValue: 310,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 475,
    baseDamage: 68,
    baseSpeed: 100,
    experienceValue: 325,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 495,
    baseDamage: 71,
    baseSpeed: 110,
    experienceValue: 340,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 10,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 515,
    baseDamage: 74,
    baseSpeed: 120,
    experienceValue: 355,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 535,
    baseDamage: 77,
    baseSpeed: 130,
    experienceValue: 370,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 10,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 555,
    baseDamage: 80,
    baseSpeed: 140,
    experienceValue: 385,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 10,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 320,
    baseDamage: 44,
    baseSpeed: 100,
    experienceValue: 205,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 340,
    baseDamage: 47,
    baseSpeed: 110,
    experienceValue: 220,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 360,
    baseDamage: 50,
    baseSpeed: 120,
    experienceValue: 235,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 12,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 380,
    baseDamage: 53,
    baseSpeed: 130,
    experienceValue: 250,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 400,
    baseDamage: 56,
    baseSpeed: 140,
    experienceValue: 265,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 420,
    baseDamage: 59,
    baseSpeed: 100,
    experienceValue: 280,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 12,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 440,
    baseDamage: 62,
    baseSpeed: 110,
    experienceValue: 295,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 460,
    baseDamage: 65,
    baseSpeed: 120,
    experienceValue: 310,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 480,
    baseDamage: 68,
    baseSpeed: 130,
    experienceValue: 325,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 12,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 500,
    baseDamage: 71,
    baseSpeed: 140,
    experienceValue: 340,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 520,
    baseDamage: 74,
    baseSpeed: 100,
    experienceValue: 355,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 540,
    baseDamage: 77,
    baseSpeed: 110,
    experienceValue: 370,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 12,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 560,
    baseDamage: 80,
    baseSpeed: 120,
    experienceValue: 385,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 580,
    baseDamage: 83,
    baseSpeed: 130,
    experienceValue: 400,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 12,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 600,
    baseDamage: 86,
    baseSpeed: 140,
    experienceValue: 415,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 12,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 365,
    baseDamage: 50,
    baseSpeed: 100,
    experienceValue: 235,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 385,
    baseDamage: 53,
    baseSpeed: 110,
    experienceValue: 250,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 405,
    baseDamage: 56,
    baseSpeed: 120,
    experienceValue: 265,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 14,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 425,
    baseDamage: 59,
    baseSpeed: 130,
    experienceValue: 280,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 445,
    baseDamage: 62,
    baseSpeed: 140,
    experienceValue: 295,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 465,
    baseDamage: 65,
    baseSpeed: 100,
    experienceValue: 310,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 14,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 485,
    baseDamage: 68,
    baseSpeed: 110,
    experienceValue: 325,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 505,
    baseDamage: 71,
    baseSpeed: 120,
    experienceValue: 340,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 525,
    baseDamage: 74,
    baseSpeed: 130,
    experienceValue: 355,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 14,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 545,
    baseDamage: 77,
    baseSpeed: 140,
    experienceValue: 370,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 565,
    baseDamage: 80,
    baseSpeed: 100,
    experienceValue: 385,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 585,
    baseDamage: 83,
    baseSpeed: 110,
    experienceValue: 400,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 14,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 605,
    baseDamage: 86,
    baseSpeed: 120,
    experienceValue: 415,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 625,
    baseDamage: 89,
    baseSpeed: 130,
    experienceValue: 430,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 14,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 645,
    baseDamage: 92,
    baseSpeed: 140,
    experienceValue: 445,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 14,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 410,
    baseDamage: 56,
    baseSpeed: 100,
    experienceValue: 265,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 430,
    baseDamage: 59,
    baseSpeed: 110,
    experienceValue: 280,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 450,
    baseDamage: 62,
    baseSpeed: 120,
    experienceValue: 295,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 16,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 470,
    baseDamage: 65,
    baseSpeed: 130,
    experienceValue: 310,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 490,
    baseDamage: 68,
    baseSpeed: 140,
    experienceValue: 325,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 510,
    baseDamage: 71,
    baseSpeed: 100,
    experienceValue: 340,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 16,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 530,
    baseDamage: 74,
    baseSpeed: 110,
    experienceValue: 355,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 550,
    baseDamage: 77,
    baseSpeed: 120,
    experienceValue: 370,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 570,
    baseDamage: 80,
    baseSpeed: 130,
    experienceValue: 385,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 16,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 590,
    baseDamage: 83,
    baseSpeed: 140,
    experienceValue: 400,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 610,
    baseDamage: 86,
    baseSpeed: 100,
    experienceValue: 415,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 630,
    baseDamage: 89,
    baseSpeed: 110,
    experienceValue: 430,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 16,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 650,
    baseDamage: 92,
    baseSpeed: 120,
    experienceValue: 445,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 670,
    baseDamage: 95,
    baseSpeed: 130,
    experienceValue: 460,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 16,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 690,
    baseDamage: 98,
    baseSpeed: 140,
    experienceValue: 475,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 16,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 455,
    baseDamage: 62,
    baseSpeed: 100,
    experienceValue: 295,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 475,
    baseDamage: 65,
    baseSpeed: 110,
    experienceValue: 310,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 495,
    baseDamage: 68,
    baseSpeed: 120,
    experienceValue: 325,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 18,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 515,
    baseDamage: 71,
    baseSpeed: 130,
    experienceValue: 340,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 535,
    baseDamage: 74,
    baseSpeed: 140,
    experienceValue: 355,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 555,
    baseDamage: 77,
    baseSpeed: 100,
    experienceValue: 370,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 18,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 575,
    baseDamage: 80,
    baseSpeed: 110,
    experienceValue: 385,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 595,
    baseDamage: 83,
    baseSpeed: 120,
    experienceValue: 400,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 615,
    baseDamage: 86,
    baseSpeed: 130,
    experienceValue: 415,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 18,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 635,
    baseDamage: 89,
    baseSpeed: 140,
    experienceValue: 430,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 655,
    baseDamage: 92,
    baseSpeed: 100,
    experienceValue: 445,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 675,
    baseDamage: 95,
    baseSpeed: 110,
    experienceValue: 460,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 18,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 695,
    baseDamage: 98,
    baseSpeed: 120,
    experienceValue: 475,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 715,
    baseDamage: 101,
    baseSpeed: 130,
    experienceValue: 490,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 18,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 735,
    baseDamage: 104,
    baseSpeed: 140,
    experienceValue: 505,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 18,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 500,
    baseDamage: 68,
    baseSpeed: 100,
    experienceValue: 325,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 520,
    baseDamage: 71,
    baseSpeed: 110,
    experienceValue: 340,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 540,
    baseDamage: 74,
    baseSpeed: 120,
    experienceValue: 355,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 20,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 560,
    baseDamage: 77,
    baseSpeed: 130,
    experienceValue: 370,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 580,
    baseDamage: 80,
    baseSpeed: 140,
    experienceValue: 385,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 600,
    baseDamage: 83,
    baseSpeed: 100,
    experienceValue: 400,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 20,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 620,
    baseDamage: 86,
    baseSpeed: 110,
    experienceValue: 415,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 640,
    baseDamage: 89,
    baseSpeed: 120,
    experienceValue: 430,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 660,
    baseDamage: 92,
    baseSpeed: 130,
    experienceValue: 445,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 20,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 680,
    baseDamage: 95,
    baseSpeed: 140,
    experienceValue: 460,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 700,
    baseDamage: 98,
    baseSpeed: 100,
    experienceValue: 475,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 720,
    baseDamage: 101,
    baseSpeed: 110,
    experienceValue: 490,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 20,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 740,
    baseDamage: 104,
    baseSpeed: 120,
    experienceValue: 505,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 760,
    baseDamage: 107,
    baseSpeed: 130,
    experienceValue: 520,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 20,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 780,
    baseDamage: 110,
    baseSpeed: 140,
    experienceValue: 535,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 20,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 545,
    baseDamage: 74,
    baseSpeed: 100,
    experienceValue: 355,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 565,
    baseDamage: 77,
    baseSpeed: 110,
    experienceValue: 370,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 585,
    baseDamage: 80,
    baseSpeed: 120,
    experienceValue: 385,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 22,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 605,
    baseDamage: 83,
    baseSpeed: 130,
    experienceValue: 400,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 625,
    baseDamage: 86,
    baseSpeed: 140,
    experienceValue: 415,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 645,
    baseDamage: 89,
    baseSpeed: 100,
    experienceValue: 430,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 22,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 665,
    baseDamage: 92,
    baseSpeed: 110,
    experienceValue: 445,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 685,
    baseDamage: 95,
    baseSpeed: 120,
    experienceValue: 460,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 705,
    baseDamage: 98,
    baseSpeed: 130,
    experienceValue: 475,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 22,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 725,
    baseDamage: 101,
    baseSpeed: 140,
    experienceValue: 490,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 745,
    baseDamage: 104,
    baseSpeed: 100,
    experienceValue: 505,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 765,
    baseDamage: 107,
    baseSpeed: 110,
    experienceValue: 520,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 22,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 785,
    baseDamage: 110,
    baseSpeed: 120,
    experienceValue: 535,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 805,
    baseDamage: 113,
    baseSpeed: 130,
    experienceValue: 550,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 22,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 825,
    baseDamage: 116,
    baseSpeed: 140,
    experienceValue: 565,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 22,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 590,
    baseDamage: 80,
    baseSpeed: 100,
    experienceValue: 385,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 610,
    baseDamage: 83,
    baseSpeed: 110,
    experienceValue: 400,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 630,
    baseDamage: 86,
    baseSpeed: 120,
    experienceValue: 415,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 24,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 650,
    baseDamage: 89,
    baseSpeed: 130,
    experienceValue: 430,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 670,
    baseDamage: 92,
    baseSpeed: 140,
    experienceValue: 445,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 690,
    baseDamage: 95,
    baseSpeed: 100,
    experienceValue: 460,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 24,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 710,
    baseDamage: 98,
    baseSpeed: 110,
    experienceValue: 475,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 730,
    baseDamage: 101,
    baseSpeed: 120,
    experienceValue: 490,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 750,
    baseDamage: 104,
    baseSpeed: 130,
    experienceValue: 505,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 24,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 770,
    baseDamage: 107,
    baseSpeed: 140,
    experienceValue: 520,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 790,
    baseDamage: 110,
    baseSpeed: 100,
    experienceValue: 535,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 810,
    baseDamage: 113,
    baseSpeed: 110,
    experienceValue: 550,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 24,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 830,
    baseDamage: 116,
    baseSpeed: 120,
    experienceValue: 565,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 850,
    baseDamage: 119,
    baseSpeed: 130,
    experienceValue: 580,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 24,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 870,
    baseDamage: 122,
    baseSpeed: 140,
    experienceValue: 595,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 24,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 635,
    baseDamage: 86,
    baseSpeed: 100,
    experienceValue: 415,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 655,
    baseDamage: 89,
    baseSpeed: 110,
    experienceValue: 430,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 675,
    baseDamage: 92,
    baseSpeed: 120,
    experienceValue: 445,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 26,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 695,
    baseDamage: 95,
    baseSpeed: 130,
    experienceValue: 460,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 715,
    baseDamage: 98,
    baseSpeed: 140,
    experienceValue: 475,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 735,
    baseDamage: 101,
    baseSpeed: 100,
    experienceValue: 490,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 26,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 755,
    baseDamage: 104,
    baseSpeed: 110,
    experienceValue: 505,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 775,
    baseDamage: 107,
    baseSpeed: 120,
    experienceValue: 520,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 795,
    baseDamage: 110,
    baseSpeed: 130,
    experienceValue: 535,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 26,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 815,
    baseDamage: 113,
    baseSpeed: 140,
    experienceValue: 550,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 835,
    baseDamage: 116,
    baseSpeed: 100,
    experienceValue: 565,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 855,
    baseDamage: 119,
    baseSpeed: 110,
    experienceValue: 580,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 26,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 875,
    baseDamage: 122,
    baseSpeed: 120,
    experienceValue: 595,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 895,
    baseDamage: 125,
    baseSpeed: 130,
    experienceValue: 610,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 26,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 915,
    baseDamage: 128,
    baseSpeed: 140,
    experienceValue: 625,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 26,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 680,
    baseDamage: 92,
    baseSpeed: 100,
    experienceValue: 445,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 700,
    baseDamage: 95,
    baseSpeed: 110,
    experienceValue: 460,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 720,
    baseDamage: 98,
    baseSpeed: 120,
    experienceValue: 475,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 28,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 740,
    baseDamage: 101,
    baseSpeed: 130,
    experienceValue: 490,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 760,
    baseDamage: 104,
    baseSpeed: 140,
    experienceValue: 505,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 780,
    baseDamage: 107,
    baseSpeed: 100,
    experienceValue: 520,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 28,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 800,
    baseDamage: 110,
    baseSpeed: 110,
    experienceValue: 535,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 820,
    baseDamage: 113,
    baseSpeed: 120,
    experienceValue: 550,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 840,
    baseDamage: 116,
    baseSpeed: 130,
    experienceValue: 565,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 28,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 860,
    baseDamage: 119,
    baseSpeed: 140,
    experienceValue: 580,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 880,
    baseDamage: 122,
    baseSpeed: 100,
    experienceValue: 595,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 900,
    baseDamage: 125,
    baseSpeed: 110,
    experienceValue: 610,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 28,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 920,
    baseDamage: 128,
    baseSpeed: 120,
    experienceValue: 625,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 940,
    baseDamage: 131,
    baseSpeed: 130,
    experienceValue: 640,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 28,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 960,
    baseDamage: 134,
    baseSpeed: 140,
    experienceValue: 655,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 28,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 725,
    baseDamage: 98,
    baseSpeed: 100,
    experienceValue: 475,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 745,
    baseDamage: 101,
    baseSpeed: 110,
    experienceValue: 490,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 765,
    baseDamage: 104,
    baseSpeed: 120,
    experienceValue: 505,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 30,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 785,
    baseDamage: 107,
    baseSpeed: 130,
    experienceValue: 520,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 805,
    baseDamage: 110,
    baseSpeed: 140,
    experienceValue: 535,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 825,
    baseDamage: 113,
    baseSpeed: 100,
    experienceValue: 550,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 30,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 845,
    baseDamage: 116,
    baseSpeed: 110,
    experienceValue: 565,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 865,
    baseDamage: 119,
    baseSpeed: 120,
    experienceValue: 580,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 885,
    baseDamage: 122,
    baseSpeed: 130,
    experienceValue: 595,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 30,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 905,
    baseDamage: 125,
    baseSpeed: 140,
    experienceValue: 610,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 925,
    baseDamage: 128,
    baseSpeed: 100,
    experienceValue: 625,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 945,
    baseDamage: 131,
    baseSpeed: 110,
    experienceValue: 640,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 30,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 965,
    baseDamage: 134,
    baseSpeed: 120,
    experienceValue: 655,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 985,
    baseDamage: 137,
    baseSpeed: 130,
    experienceValue: 670,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 30,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1005,
    baseDamage: 140,
    baseSpeed: 140,
    experienceValue: 685,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 30,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 770,
    baseDamage: 104,
    baseSpeed: 100,
    experienceValue: 505,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 790,
    baseDamage: 107,
    baseSpeed: 110,
    experienceValue: 520,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 810,
    baseDamage: 110,
    baseSpeed: 120,
    experienceValue: 535,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 32,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 830,
    baseDamage: 113,
    baseSpeed: 130,
    experienceValue: 550,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 850,
    baseDamage: 116,
    baseSpeed: 140,
    experienceValue: 565,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 870,
    baseDamage: 119,
    baseSpeed: 100,
    experienceValue: 580,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 32,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 890,
    baseDamage: 122,
    baseSpeed: 110,
    experienceValue: 595,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 910,
    baseDamage: 125,
    baseSpeed: 120,
    experienceValue: 610,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 930,
    baseDamage: 128,
    baseSpeed: 130,
    experienceValue: 625,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 32,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 950,
    baseDamage: 131,
    baseSpeed: 140,
    experienceValue: 640,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 970,
    baseDamage: 134,
    baseSpeed: 100,
    experienceValue: 655,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 990,
    baseDamage: 137,
    baseSpeed: 110,
    experienceValue: 670,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 32,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 1010,
    baseDamage: 140,
    baseSpeed: 120,
    experienceValue: 685,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 1030,
    baseDamage: 143,
    baseSpeed: 130,
    experienceValue: 700,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 32,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1050,
    baseDamage: 146,
    baseSpeed: 140,
    experienceValue: 715,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 32,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 815,
    baseDamage: 110,
    baseSpeed: 100,
    experienceValue: 535,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 835,
    baseDamage: 113,
    baseSpeed: 110,
    experienceValue: 550,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 855,
    baseDamage: 116,
    baseSpeed: 120,
    experienceValue: 565,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 34,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 875,
    baseDamage: 119,
    baseSpeed: 130,
    experienceValue: 580,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 895,
    baseDamage: 122,
    baseSpeed: 140,
    experienceValue: 595,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 915,
    baseDamage: 125,
    baseSpeed: 100,
    experienceValue: 610,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 34,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 935,
    baseDamage: 128,
    baseSpeed: 110,
    experienceValue: 625,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 955,
    baseDamage: 131,
    baseSpeed: 120,
    experienceValue: 640,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 975,
    baseDamage: 134,
    baseSpeed: 130,
    experienceValue: 655,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 34,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 995,
    baseDamage: 137,
    baseSpeed: 140,
    experienceValue: 670,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 1015,
    baseDamage: 140,
    baseSpeed: 100,
    experienceValue: 685,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 1035,
    baseDamage: 143,
    baseSpeed: 110,
    experienceValue: 700,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 34,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 1055,
    baseDamage: 146,
    baseSpeed: 120,
    experienceValue: 715,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 1075,
    baseDamage: 149,
    baseSpeed: 130,
    experienceValue: 730,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 34,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1095,
    baseDamage: 152,
    baseSpeed: 140,
    experienceValue: 745,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 34,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 860,
    baseDamage: 116,
    baseSpeed: 100,
    experienceValue: 565,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 880,
    baseDamage: 119,
    baseSpeed: 110,
    experienceValue: 580,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 900,
    baseDamage: 122,
    baseSpeed: 120,
    experienceValue: 595,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 36,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 920,
    baseDamage: 125,
    baseSpeed: 130,
    experienceValue: 610,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 940,
    baseDamage: 128,
    baseSpeed: 140,
    experienceValue: 625,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 960,
    baseDamage: 131,
    baseSpeed: 100,
    experienceValue: 640,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 36,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 980,
    baseDamage: 134,
    baseSpeed: 110,
    experienceValue: 655,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 1000,
    baseDamage: 137,
    baseSpeed: 120,
    experienceValue: 670,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 1020,
    baseDamage: 140,
    baseSpeed: 130,
    experienceValue: 685,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 36,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 1040,
    baseDamage: 143,
    baseSpeed: 140,
    experienceValue: 700,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 1060,
    baseDamage: 146,
    baseSpeed: 100,
    experienceValue: 715,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 1080,
    baseDamage: 149,
    baseSpeed: 110,
    experienceValue: 730,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 36,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 1100,
    baseDamage: 152,
    baseSpeed: 120,
    experienceValue: 745,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 1120,
    baseDamage: 155,
    baseSpeed: 130,
    experienceValue: 760,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 36,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1140,
    baseDamage: 158,
    baseSpeed: 140,
    experienceValue: 775,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 36,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 905,
    baseDamage: 122,
    baseSpeed: 100,
    experienceValue: 595,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 925,
    baseDamage: 125,
    baseSpeed: 110,
    experienceValue: 610,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 945,
    baseDamage: 128,
    baseSpeed: 120,
    experienceValue: 625,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 38,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 965,
    baseDamage: 131,
    baseSpeed: 130,
    experienceValue: 640,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 985,
    baseDamage: 134,
    baseSpeed: 140,
    experienceValue: 655,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 1005,
    baseDamage: 137,
    baseSpeed: 100,
    experienceValue: 670,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 38,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 1025,
    baseDamage: 140,
    baseSpeed: 110,
    experienceValue: 685,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 1045,
    baseDamage: 143,
    baseSpeed: 120,
    experienceValue: 700,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 1065,
    baseDamage: 146,
    baseSpeed: 130,
    experienceValue: 715,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 38,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 1085,
    baseDamage: 149,
    baseSpeed: 140,
    experienceValue: 730,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 1105,
    baseDamage: 152,
    baseSpeed: 100,
    experienceValue: 745,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 1125,
    baseDamage: 155,
    baseSpeed: 110,
    experienceValue: 760,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 38,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 1145,
    baseDamage: 158,
    baseSpeed: 120,
    experienceValue: 775,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 1165,
    baseDamage: 161,
    baseSpeed: 130,
    experienceValue: 790,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 38,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1185,
    baseDamage: 164,
    baseSpeed: 140,
    experienceValue: 805,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 38,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Warrior',
    baseHealth: 950,
    baseDamage: 128,
    baseSpeed: 100,
    experienceValue: 625,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Skeleton Archer',
    baseHealth: 970,
    baseDamage: 131,
    baseSpeed: 110,
    experienceValue: 640,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Zombie Brute',
    baseHealth: 990,
    baseDamage: 134,
    baseSpeed: 120,
    experienceValue: 655,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 40,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Crypt Ghoul',
    baseHealth: 1010,
    baseDamage: 137,
    baseSpeed: 130,
    experienceValue: 670,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Shadow Wraith',
    baseHealth: 1030,
    baseDamage: 140,
    baseSpeed: 140,
    experienceValue: 685,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Infernal Imp',
    baseHealth: 1050,
    baseDamage: 143,
    baseSpeed: 100,
    experienceValue: 700,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 40,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Hellhound',
    baseHealth: 1070,
    baseDamage: 146,
    baseSpeed: 110,
    experienceValue: 715,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Magma Golem',
    baseHealth: 1090,
    baseDamage: 149,
    baseSpeed: 120,
    experienceValue: 730,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Frost Revenant',
    baseHealth: 1110,
    baseDamage: 152,
    baseSpeed: 130,
    experienceValue: 745,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 40,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Ice Stalker',
    baseHealth: 1130,
    baseDamage: 155,
    baseSpeed: 140,
    experienceValue: 760,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Thunder Wyrm',
    baseHealth: 1150,
    baseDamage: 158,
    baseSpeed: 100,
    experienceValue: 775,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'boss_titans',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Storm Elemental',
    baseHealth: 1170,
    baseDamage: 161,
    baseSpeed: 110,
    experienceValue: 790,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 40,
    },
    behaviorTreeType: 'stealth_ambusher',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Corrupted Druid',
    baseHealth: 1190,
    baseDamage: 164,
    baseSpeed: 120,
    experienceValue: 805,
    resistances: {
      fire: 50,
      cold: 0,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'melee_swarmer',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Abyssal Behemoth',
    baseHealth: 1210,
    baseDamage: 167,
    baseSpeed: 130,
    experienceValue: 820,
    resistances: {
      fire: 0,
      cold: 50,
      lightning: 0,
      physical: 40,
    },
    behaviorTreeType: 'ranged_caster',
  },
  {
    id: 'mob_t${tier}_${m}',
    name: 'Tier ${tier} Void Harvester',
    baseHealth: 1230,
    baseDamage: 170,
    baseSpeed: 140,
    experienceValue: 835,
    resistances: {
      fire: 0,
      cold: 0,
      lightning: 50,
      physical: 40,
    },
    behaviorTreeType: 'boss_titans',
  },
];

export class MonsterEncounterTables {
  public static getEncountersForTier(tier: number): MonsterArchetype[] {
    return BESTIARY.filter(m => m.id.startsWith(`mob_t${tier}_`));
  }
}
