/**
 * @file QuestCatalog.ts
 * @description Complete campaign storyline quests spanning 10 Chapters, bounties, and dungeon boss hunts.
 */

import { type Quest, QuestState } from './QuestManager.ts';

export const CAMPAIGN_QUESTS: Quest[] = [
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.Active,
    xpReward: 620,
    goldReward: 330,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 8,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 740,
    goldReward: 410,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 9,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 860,
    goldReward: 490,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 10,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 980,
    goldReward: 570,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 11,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1100,
    goldReward: 650,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 12,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1220,
    goldReward: 730,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 13,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1340,
    goldReward: 810,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 14,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1460,
    goldReward: 890,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 15,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1120,
    goldReward: 580,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 10,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1240,
    goldReward: 660,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 11,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1360,
    goldReward: 740,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 12,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1480,
    goldReward: 820,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 13,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1600,
    goldReward: 900,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 14,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1720,
    goldReward: 980,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 15,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1840,
    goldReward: 1060,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 16,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1960,
    goldReward: 1140,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 17,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1620,
    goldReward: 830,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 12,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1740,
    goldReward: 910,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 13,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1860,
    goldReward: 990,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 14,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 1980,
    goldReward: 1070,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 15,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2100,
    goldReward: 1150,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 16,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2220,
    goldReward: 1230,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 17,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2340,
    goldReward: 1310,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 18,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2460,
    goldReward: 1390,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 19,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2120,
    goldReward: 1080,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 14,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2240,
    goldReward: 1160,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 15,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2360,
    goldReward: 1240,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 16,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2480,
    goldReward: 1320,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 17,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2600,
    goldReward: 1400,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 18,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2720,
    goldReward: 1480,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 19,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2840,
    goldReward: 1560,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 20,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2960,
    goldReward: 1640,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 21,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2620,
    goldReward: 1330,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 16,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2740,
    goldReward: 1410,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 17,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2860,
    goldReward: 1490,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 18,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 2980,
    goldReward: 1570,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 19,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3100,
    goldReward: 1650,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 20,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3220,
    goldReward: 1730,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 21,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3340,
    goldReward: 1810,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 22,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3460,
    goldReward: 1890,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 23,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3120,
    goldReward: 1580,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 18,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3240,
    goldReward: 1660,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 19,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3360,
    goldReward: 1740,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 20,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3480,
    goldReward: 1820,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 21,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3600,
    goldReward: 1900,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 22,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3720,
    goldReward: 1980,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 23,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3840,
    goldReward: 2060,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 24,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3960,
    goldReward: 2140,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 25,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3620,
    goldReward: 1830,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 20,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3740,
    goldReward: 1910,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 21,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3860,
    goldReward: 1990,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 22,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 3980,
    goldReward: 2070,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 23,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4100,
    goldReward: 2150,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 24,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4220,
    goldReward: 2230,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 25,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4340,
    goldReward: 2310,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 26,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4460,
    goldReward: 2390,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 27,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4120,
    goldReward: 2080,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 22,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4240,
    goldReward: 2160,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 23,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4360,
    goldReward: 2240,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 24,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4480,
    goldReward: 2320,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 25,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4600,
    goldReward: 2400,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 26,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4720,
    goldReward: 2480,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 27,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4840,
    goldReward: 2560,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 28,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4960,
    goldReward: 2640,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 29,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4620,
    goldReward: 2330,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 24,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4740,
    goldReward: 2410,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 25,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4860,
    goldReward: 2490,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 26,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 4980,
    goldReward: 2570,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 27,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5100,
    goldReward: 2650,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 28,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5220,
    goldReward: 2730,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 29,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5340,
    goldReward: 2810,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 30,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5460,
    goldReward: 2890,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 31,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5120,
    goldReward: 2580,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 26,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5240,
    goldReward: 2660,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 27,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5360,
    goldReward: 2740,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 28,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5480,
    goldReward: 2820,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 29,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5600,
    goldReward: 2900,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 30,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5720,
    goldReward: 2980,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 31,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5840,
    goldReward: 3060,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 32,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
  {
    id: 'quest_act${act}_${q}',
    title: 'Act ${act}: Chapter ${q} - The Awakening of Aether',
    description: 'Venture forth into the depths to clear out corruption and restore balance to the ley lines.',
    state: QuestState.NotStarted,
    xpReward: 5960,
    goldReward: 3140,
    objectives: [
      {
        description: 'Slay corrupted abominations in the lower sanctum',
        targetCount: 33,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Recover the ancient Aether Core fragment',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
      {
        description: 'Speak with Archmage Vaelin at the town spire',
        targetCount: 1,
        currentCount: 0,
        isComplete: false,
      },
    ],
  },
];

export class QuestCatalog {
  public static getAllQuests(): Quest[] {
    return CAMPAIGN_QUESTS;
  }
}
